import { AfterViewInit, EventEmitter, OnChanges, SimpleChanges, TemplateRef } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { MatSort, Sort } from '@angular/material/sort';
import { PageEvent } from '@angular/material/paginator';
import { SelectionModel } from '@angular/cdk/collections';
import { BooleanInput } from '@angular/cdk/coercion';
import { DscPaginatorComponent } from 'sidsc-components/dsc-paginator';
import { DscTableColumn } from './shared/dsc-table-column';
import { MatInput } from '@angular/material/input';
import * as i0 from "@angular/core";
export type DscTableSelectorType = 'checkbox' | 'radio-button';
export declare class DscTableComponent<T> implements AfterViewInit, OnChanges {
    matSort: MatSort;
    dscPaginator: DscPaginatorComponent;
    customActionButtons: TemplateRef<any>;
    columns: DscTableColumn[];
    data: T[];
    paginatorPageIndex: number;
    paginatorLength: number;
    paginatorPageSize: number;
    pageSizeOptions: number[];
    selectorType?: DscTableSelectorType;
    expandedDetailTemplate: TemplateRef<any>;
    tableMaxHeight?: string;
    tableRowHeight?: string;
    selectedItems: T[];
    showUnsortedIcon: boolean;
    footerFixed: boolean;
    get emptyMessageData(): string;
    set emptyMessageData(value: string);
    private _emptyMessageData;
    get paginator(): boolean;
    set paginator(value: BooleanInput);
    private _paginator;
    get backendPagination(): boolean;
    set backendPagination(value: BooleanInput);
    private _backendPagination;
    get emitPageEventAfterView(): boolean;
    set emitPageEventAfterView(value: BooleanInput);
    private _emitPageEventAfterView;
    get expandable(): boolean;
    set expandable(value: BooleanInput);
    private _expandable;
    get showFirstLastButtons(): boolean;
    set showFirstLastButtons(value: BooleanInput);
    get hidePageSize(): boolean;
    set hidePageSize(value: BooleanInput);
    get showPageSizeOptions(): boolean;
    set showPageSizeOptions(value: BooleanInput);
    get hidePaginatorRangeLabel(): boolean;
    set hidePaginatorRangeLabel(value: BooleanInput);
    get disabledPaginator(): boolean;
    set disabledPaginator(value: BooleanInput);
    get expandMultiple(): boolean;
    set expandMultiple(value: BooleanInput);
    matInput: MatInput;
    private _hidePaginatorRangeLabel;
    private _showFirstLastButtons;
    private _hidePageSize;
    private _showPageSizeOptions;
    private _disabledPaginator;
    private _expandMultiple;
    private lastSort?;
    tooltipId: string;
    page: EventEmitter<PageEvent>;
    selectionChange: EventEmitter<T[]>;
    checkboxChange: EventEmitter<T[]>;
    radioButtonChange: EventEmitter<T>;
    sortChange: EventEmitter<Sort>;
    rowExpanded: EventEmitter<any>;
    selection: SelectionModel<T>;
    radioButtonSelected?: T;
    displayedColumns: any[];
    dataSource: MatTableDataSource<T>;
    expandedElement: T;
    labelHintTooltip: boolean;
    expandedElements: any[];
    currentDirection: 'asc' | 'desc' | '';
    checkboxAllLabel: string;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private _setInitialSelection;
    private isNumeric;
    private _tableInit;
    private _createDataSource;
    private _setColumns;
    private _getCurrentPageData;
    onPage(pageEvent: PageEvent): void;
    onSortChange(sort: Sort): void;
    getSortIcon(column: any): string;
    getFooterValue(col: DscTableColumn): any;
    get hasFooter(): boolean;
    isExpanded(row: any): boolean;
    isAllSelected(): boolean;
    toggleAllRows(): void;
    toggleAllRowsWithPaginator(): void;
    toggleAllRowsNoPaginator(): void;
    checkboxLabel(row?: T): string;
    onSelectionChange(): void;
    onSelectChange($event: any, row: T): void;
    onRadioButtonChange(row: T): void;
    onClick(row: any, $event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscTableComponent<any>, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscTableComponent<any>, "dsc-table", never, { "columns": { "alias": "columns"; "required": false; }; "data": { "alias": "data"; "required": false; }; "paginatorPageIndex": { "alias": "paginatorPageIndex"; "required": false; }; "paginatorLength": { "alias": "paginatorLength"; "required": false; }; "paginatorPageSize": { "alias": "paginatorPageSize"; "required": false; }; "pageSizeOptions": { "alias": "pageSizeOptions"; "required": false; }; "selectorType": { "alias": "selectorType"; "required": false; }; "expandedDetailTemplate": { "alias": "expandedDetailTemplate"; "required": false; }; "tableMaxHeight": { "alias": "tableMaxHeight"; "required": false; }; "tableRowHeight": { "alias": "tableRowHeight"; "required": false; }; "selectedItems": { "alias": "selectedItems"; "required": false; }; "showUnsortedIcon": { "alias": "showUnsortedIcon"; "required": false; }; "footerFixed": { "alias": "footerFixed"; "required": false; }; "emptyMessageData": { "alias": "emptyMessageData"; "required": false; }; "paginator": { "alias": "paginator"; "required": false; }; "backendPagination": { "alias": "backendPagination"; "required": false; }; "emitPageEventAfterView": { "alias": "emitPageEventAfterView"; "required": false; }; "expandable": { "alias": "expandable"; "required": false; }; "showFirstLastButtons": { "alias": "showFirstLastButtons"; "required": false; }; "hidePageSize": { "alias": "hidePageSize"; "required": false; }; "showPageSizeOptions": { "alias": "showPageSizeOptions"; "required": false; }; "hidePaginatorRangeLabel": { "alias": "hidePaginatorRangeLabel"; "required": false; }; "disabledPaginator": { "alias": "disabledPaginator"; "required": false; }; "expandMultiple": { "alias": "expandMultiple"; "required": false; }; }, { "page": "page"; "selectionChange": "selectionChange"; "checkboxChange": "checkboxChange"; "radioButtonChange": "radioButtonChange"; "sortChange": "sortChange"; "rowExpanded": "rowExpanded"; }, ["customActionButtons"], never, true, never>;
}
