import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { FormControl, FormGroupDirective, NgControl, NgForm } from '@angular/forms';
import { MatInput } from '@angular/material/input';
import { BaseComponent } from 'sidsc-components/core';
import * as i0 from "@angular/core";
export declare class DscInputComponent extends BaseComponent<any> implements OnInit, AfterViewInit {
    ngControl: NgControl;
    private cdr;
    matInput: MatInput;
    keydown: EventEmitter<any>;
    search: EventEmitter<string>;
    suffix: string;
    mask?: string;
    dropSpecialCharacters: boolean;
    iconPrefix?: string;
    iconSuffix?: string;
    iconStyle: 'outlined' | 'filled' | 'rounded' | 'sharp' | 'two-tone';
    options: string[];
    autocompleteControl: FormControl<string | null>;
    get showCharCounter(): boolean;
    set showCharCounter(value: boolean | string);
    isActive: boolean;
    tooltipId: string;
    private _showCharCounter;
    get showClearButton(): boolean;
    set showClearButton(value: boolean | string);
    private _showClearButton;
    hidePassword: boolean;
    filteredOptions: string[];
    inputEl: ElementRef<HTMLInputElement>;
    constructor(ngControl: NgControl, parentForm: NgForm, parentFormGroup: FormGroupDirective, cdr: ChangeDetectorRef);
    ngOnInit(): void;
    specialCharacters(value: any): void;
    private _filter;
    ngAfterViewInit(): void;
    onInput(event: Event): void;
    onOptionSelected(event: any): void;
    get formFieldClasses(): string[];
    getIconClass(): string;
    onKeydown($event: KeyboardEvent): void;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscInputComponent, [{ optional: true; self: true; }, { optional: true; }, { optional: true; }, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscInputComponent, "dsc-input", never, { "suffix": { "alias": "suffix"; "required": false; }; "mask": { "alias": "mask"; "required": false; }; "dropSpecialCharacters": { "alias": "dropSpecialCharacters"; "required": false; }; "iconPrefix": { "alias": "iconPrefix"; "required": false; }; "iconSuffix": { "alias": "iconSuffix"; "required": false; }; "iconStyle": { "alias": "iconStyle"; "required": false; }; "options": { "alias": "options"; "required": false; }; "autocompleteControl": { "alias": "autocompleteControl"; "required": false; }; "showCharCounter": { "alias": "showCharCounter"; "required": false; }; "showClearButton": { "alias": "showClearButton"; "required": false; }; }, { "keydown": "keydown"; "search": "search"; }, never, never, true, never>;
}
