import { TemplateRef } from '@angular/core';
export type DscTableColumnAlign = 'left' | 'center' | 'right';
export type DscTableFixed = 'rowTop' | 'rowBottom' | 'columnLeft' | 'columnRight' | 'header' | undefined;
export type DscTableOrder = 'asc' | 'desc' | '';
export declare class DscTableColumn {
    title: string | undefined;
    property: string;
    value: Function;
    width: number | undefined;
    headerAlign: DscTableColumnAlign;
    bodyCellAlign: DscTableColumnAlign;
    sortable: boolean;
    sortID: string;
    sortableActive: boolean;
    showUnsortedIcon: boolean;
    currentDirection: DscTableOrder;
    footerTitle: string;
    footerCalc: Function;
    fixed: DscTableFixed;
    headerFixed: boolean;
    headerTooltip: string;
    headerTooltipVariant: boolean;
    template: TemplateRef<any> | undefined;
    private _title?;
    private _property;
    private _value;
    private _width?;
    private _headerAlign;
    private _bodyCellAlign;
    private _sortable;
    private _sortID;
    private _sortableActive;
    private _showUnsortedIcon;
    private _currentDirection;
    private _footerTitle?;
    private _footerCalc?;
    private _fixed?;
    private _headerFixed?;
    private _headerTooltip?;
    private _headerTooltipVariant?;
    private _template?;
    constructor(title: string | undefined, property: string, value: Function, width: number | undefined, headerAlign: DscTableColumnAlign, bodyCellAlign: DscTableColumnAlign, sortable: boolean, sortID: string, sortableActive: boolean, showUnsortedIcon: boolean, currentDirection: DscTableOrder, footerTitle: string, footerCalc: Function, fixed: DscTableFixed, headerFixed: boolean, headerTooltip: string, headerTooltipVariant: boolean, template: TemplateRef<any> | undefined);
}
