import { TemplateRef } from '@angular/core';
import { NumberInput } from '@angular/cdk/coercion';
import { DscTableColumn, DscTableColumnAlign, DscTableFixed, DscTableOrder } from './dsc-table-column';
export declare class DscTableColumnBuilder {
    private _title?;
    private _property;
    private _value;
    private _width?;
    private _headerAlign;
    private _bodyCellAlign;
    private _sortable;
    private _sortID;
    private _sortableActive;
    private _showUnsortedIcon;
    private _currentDirection;
    private _footerTitle;
    private _footerCalc?;
    private _fixed;
    private _headerFixed;
    private _headerTooltip;
    private _headerTooltipVariant;
    private _template?;
    static instance(): DscTableColumnBuilder;
    title(title: string): DscTableColumnBuilder;
    property(property: string): DscTableColumnBuilder;
    value(value: any): DscTableColumnBuilder;
    width(width: NumberInput): DscTableColumnBuilder;
    headerAlign(headerAlign: DscTableColumnAlign): DscTableColumnBuilder;
    bodyCellAlign(bodyCellAlign: DscTableColumnAlign): DscTableColumnBuilder;
    sortable(sortable: boolean): DscTableColumnBuilder;
    sortID(sortID: string): DscTableColumnBuilder;
    sortableActive(sortableActive: boolean): DscTableColumnBuilder;
    showUnsortedIcon(showUnsortedIcon: boolean): DscTableColumnBuilder;
    currentDirection(currentDirection: DscTableOrder): DscTableColumnBuilder;
    footerTitle(footerTitle: string): DscTableColumnBuilder;
    footerCalc(footerCalc: any): DscTableColumnBuilder;
    fixed(fixed: DscTableFixed): DscTableColumnBuilder;
    headerFixed(headerFixed: boolean): DscTableColumnBuilder;
    headerTooltip(headerTooltip: string): DscTableColumnBuilder;
    headerTooltipVariant(headerTooltipVariant: boolean): DscTableColumnBuilder;
    template(template: TemplateRef<any>): DscTableColumnBuilder;
    build(): DscTableColumn;
}
