trigger:
  branches:
    include:
      - develop
      - master

pool:
  name: 'Servidor025Pool'

variables:
  environment: 'development'
  siteName: '1002sigvc.des.caixa'
  websitePath: 'E:\Websites\1002sigvc.des.caixa'
  distFrontend: 'dist/front-gc-painel-gerencial'

steps:
- script: |
    echo "Definindo variáveis de ambiente..."
    if "%Build_SourceBranchName%"=="master" (
        echo ##vso[task.setvariable variable=environment]production
        echo ##vso[task.setvariable variable=siteName]1002sigvc.des.caixa
        echo ##vso[task.setvariable variable=websitePath]E:\Websites\1002sigvc.des.caixa
    ) else (
        echo ##vso[task.setvariable variable=environment]development
        echo ##vso[task.setvariable variable=siteName]1002sigvc.des.caixa
        echo ##vso[task.setvariable variable=websitePath]E:\Websites\1002sigvc.des.caixa
    )
  displayName: 'Definir Variáveis de Ambiente'

- script: |
    echo "Parando instância do IIS..."
    C:\Windows\System32\inetsrv\appcmd.exe stop site /site.name:"$(siteName)"
  displayName: 'Parando instância do IIS'
- script: |
    echo "Adicionando Node.js ao PATH..."
    set PATH=C:\Program Files\nodejs;%PATH%
    node -v
    npm -v
  displayName: 'Configurar Node.js no PATH'

- script: |
    echo "Configurando binario.caixa..."
    C:\Windows\System32\inetsrv\appcmd.exe npm config set proxy http://binario.caixa:8081/repository/npm-all/
    C:\Windows\System32\inetsrv\appcmd.exe npm config set https_proxy http://binario.caixa:8081/repository/npm-all/
    C:\Windows\System32\inetsrv\appcmd.exe npm config set registry http://binario.caixa:8081/repository/npm-all/
  displayName: 'Parando instância do IIS'

- script: |
    echo "Instalando dependências do projeto..."
    set PATH=C:\Program Files\nodejs;%PATH%
    npm install
  displayName: 'Instalar Dependências'
- script: |
    echo "Executando build do Angular para $(environment)..."
    set PATH=C:\Program Files\nodejs;%PATH%
    npm run build -- --configuration $(environment)
  displayName: 'Build do Angular'
- script: |
    echo "Limpando arquivos do diretório IIS em $(websitePath)..."
    for /d %%d in ("$(websitePath)\*") do rmdir /S /Q "%%d"
    del /Q "$(websitePath)\*"
  displayName: 'Limpando diretório do IIS'
- task: CopyFiles@2
  displayName: 'Copiar arquivos para IIS'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/$(distFrontend)'
    Contents: '**/*'
    TargetFolder: "$(websitePath)"
    OverWrite: true
- script: |
    echo "Iniciando instância do IIS..."
    C:\Windows\System32\inetsrv\appcmd.exe start site /site.name:"$(siteName)"
  displayName: 'Iniciando instância do IIS'
- script: |
    echo "DEPLOY FINALIZADO para $(environment)"
  displayName: 'Finalização do Deploy'