import { EventEmitter } from '@angular/core';
import { AbstractControl, ValidationErrors, Validator } from '@angular/forms';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { BooleanInput } from '@angular/cdk/coercion';
import { BaseControlValueAccessor } from 'sidsc-components/core';
import * as i0 from "@angular/core";
export type DscCheckboxLabelPosition = 'before' | 'after';
export type DscCheckboxVariant = 'highlight' | 'accent' | 'danger';
export type DscCheckboxSize = 'large' | 'standard' | 'small';
export declare class DscCheckboxComponent extends BaseControlValueAccessor<BooleanInput> implements Validator {
    labelPosition: DscCheckboxLabelPosition;
    name: string;
    label?: string;
    ariaDescribedby: string;
    ariaLabel: string;
    ariaLabelledby: string | null;
    get indeterminate(): boolean;
    set indeterminate(value: BooleanInput);
    private _indeterminate;
    get checked(): boolean;
    set checked(value: BooleanInput);
    private _checked;
    get required(): boolean;
    set required(value: BooleanInput);
    private _required;
    get size(): DscCheckboxSize;
    set size(value: DscCheckboxSize);
    private _size;
    protected checkboxLabelSize: string;
    get variant(): DscCheckboxVariant;
    set variant(value: DscCheckboxVariant);
    private _variant;
    protected checkboxVariant: string;
    readonly change: EventEmitter<any>;
    readonly indeterminateChange: EventEmitter<boolean>;
    onChanged($event: MatCheckboxChange): void;
    onIndeterminateChange(value: boolean): void;
    toggle(): void;
    writeValue(value: BooleanInput): void;
    validate(control: AbstractControl<any, any>): ValidationErrors | null;
    get disabled(): boolean;
    set disabled(value: BooleanInput);
    private _disable;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscCheckboxComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscCheckboxComponent, "dsc-checkbox", never, { "labelPosition": { "alias": "labelPosition"; "required": false; }; "name": { "alias": "name"; "required": false; }; "label": { "alias": "label"; "required": false; }; "ariaDescribedby": { "alias": "aria-describedby"; "required": false; }; "ariaLabel": { "alias": "aria-label"; "required": false; }; "ariaLabelledby": { "alias": "aria-labelledby"; "required": false; }; "indeterminate": { "alias": "indeterminate"; "required": false; }; "checked": { "alias": "checked"; "required": false; }; "required": { "alias": "required"; "required": false; }; "size": { "alias": "size"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; }, { "change": "change"; "indeterminateChange": "indeterminateChange"; }, never, never, true, never>;
}
