import { EventEmitter } from '@angular/core';
import { FormGroupDirective, NgControl, NgForm } from '@angular/forms';
import { FieldErrorMessengerService } from './services/field-error-messenger.service';
import { BaseControlValueAccessor } from './base-control-value-accessor';
import { CustomErrorStateMatcher } from './custom-error-state-matcher';
import * as i0 from "@angular/core";
type Size = 'large' | 'standard' | 'small';
type Type = 'text' | 'password' | 'number';
export declare class BaseComponent<T> extends BaseControlValueAccessor<T> {
    private _ngControl;
    private _parentForm;
    private _parentFormGroup;
    protected errorMessageService: FieldErrorMessengerService;
    blur: EventEmitter<any>;
    label?: string;
    labelHint?: string;
    labelHintTooltip?: string;
    name: string;
    placeholder: string;
    formFieldHint: string;
    errorMessage?: string;
    showIconPassword: boolean;
    readOnly: boolean;
    ariaDescribedby: string;
    ariaLabel: string;
    ariaLabelledby: string | null;
    get type(): Type;
    set type(value: Type);
    private _type;
    protected isPasswordField: boolean;
    get size(): Size;
    set size(value: Size);
    private _size;
    protected formFieldLabelSize: string;
    protected formFieldSize: string;
    protected selectOptionSize: string;
    protected selectOption: string;
    get maxlength(): number;
    set maxlength(value: number | string);
    private _maxlength;
    constructor(_ngControl: NgControl, _parentForm: NgForm, _parentFormGroup: FormGroupDirective);
    protected matcher: CustomErrorStateMatcher;
    get errorText(): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<BaseComponent<any>, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BaseComponent<any>, "ng-component", never, { "label": { "alias": "label"; "required": false; }; "labelHint": { "alias": "labelHint"; "required": false; }; "labelHintTooltip": { "alias": "labelHintTooltip"; "required": false; }; "name": { "alias": "name"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "formFieldHint": { "alias": "formFieldHint"; "required": false; }; "errorMessage": { "alias": "errorMessage"; "required": false; }; "showIconPassword": { "alias": "showIconPassword"; "required": false; }; "readOnly": { "alias": "readOnly"; "required": false; }; "ariaDescribedby": { "alias": "aria-describedby"; "required": false; }; "ariaLabel": { "alias": "aria-label"; "required": false; }; "ariaLabelledby": { "alias": "aria-labelledby"; "required": false; }; "type": { "alias": "type"; "required": false; }; "size": { "alias": "size"; "required": false; }; "maxlength": { "alias": "maxlength"; "required": false; }; }, { "blur": "blur"; }, never, never, true, never>;
}
export {};
