import { EventEmitter } from '@angular/core';
import { AbstractControl, ValidationErrors, Validator } from '@angular/forms';
import { MatSlideToggleChange } from '@angular/material/slide-toggle';
import { BooleanInput } from '@angular/cdk/coercion';
import { BaseControlValueAccessor } from 'sidsc-components/core';
import * as i0 from "@angular/core";
type DscSwitchLabelPosition = 'before' | 'after';
type DscSwitchVariant = 'highlight' | 'accent' | 'danger';
type DscSwitchSize = 'large' | 'standard' | 'small';
export declare class DscSwitchComponent extends BaseControlValueAccessor<BooleanInput> implements Validator {
    switchClasses: any;
    labelPosition: DscSwitchLabelPosition;
    name: string;
    label?: string;
    ariaDescribedby: string;
    ariaLabel: string;
    ariaLabelledby: string | null;
    get disabled(): boolean;
    set disabled(value: BooleanInput);
    get checked(): boolean;
    set checked(value: BooleanInput);
    private _checked;
    get required(): boolean;
    set required(value: BooleanInput);
    private _required;
    get size(): DscSwitchSize;
    set size(value: DscSwitchSize);
    private _size;
    protected switchLabelSize: string;
    get variant(): DscSwitchVariant;
    set variant(value: DscSwitchVariant);
    private _variant;
    protected switchVariant: string;
    get hideIcon(): boolean;
    set hideIcon(value: BooleanInput);
    private _hideIcon;
    readonly change: EventEmitter<any>;
    readonly toggleChange: EventEmitter<void>;
    toggle(): void;
    writeValue(value: BooleanInput): void;
    onChanged($event: MatSlideToggleChange): void;
    onToggleChange(): void;
    validate(control: AbstractControl<any, any>): ValidationErrors | null;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscSwitchComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscSwitchComponent, "dsc-switch", never, { "labelPosition": { "alias": "labelPosition"; "required": false; }; "name": { "alias": "name"; "required": false; }; "label": { "alias": "label"; "required": false; }; "ariaDescribedby": { "alias": "aria-describedby"; "required": false; }; "ariaLabel": { "alias": "aria-label"; "required": false; }; "ariaLabelledby": { "alias": "aria-labelledby"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "checked": { "alias": "checked"; "required": false; }; "required": { "alias": "required"; "required": false; }; "size": { "alias": "size"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; "hideIcon": { "alias": "hideIcon"; "required": false; }; }, { "change": "change"; "toggleChange": "toggleChange"; }, never, never, true, never>;
}
export {};
