import { OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { BooleanInput } from '@angular/cdk/coercion';
import * as i0 from "@angular/core";
export type MaterialButtonVariant = 'icon-button' | 'unelevated-button' | 'outlined-button' | 'button-base';
export type DscButtonVariant = 'primary' | 'secondary' | 'danger' | 'secondary-outlined' | 'danger-outlined' | 'auxiliary' | 'secondary-text' | 'secondary-text-inverse' | 'danger-text' | undefined;
export type DscButtonSize = 'large' | 'standard' | 'small';
export type DscButtonType = 'button' | 'submit';
export declare class DscButtonComponent implements OnInit, OnChanges {
    type: DscButtonType;
    label?: string;
    iconSuffix?: string;
    iconPrefix?: string;
    icon?: string;
    tabIndex: number;
    dscTooltip?: string;
    ariaLabel?: string;
    ariaExpanded?: boolean | null;
    ariaControls?: string | null;
    iconStyle: 'outlined' | 'filled' | 'rounded' | 'sharp' | 'two-tone';
    get variant(): DscButtonVariant;
    set variant(value: DscButtonVariant);
    private _variant;
    get size(): any;
    set size(value: DscButtonSize);
    private _size;
    sizeIcon: string;
    get disabled(): boolean;
    set disabled(value: boolean | string);
    private _disabled;
    get isDisabled(): true | null;
    get iconButton(): boolean;
    set iconButton(value: BooleanInput);
    private _iconButton;
    variantButtonClass: string;
    pressedByEnter: boolean;
    ngOnInit(): void;
    onKeyDown(event: KeyboardEvent): void;
    onKeyUp(event: KeyboardEvent): void;
    private _setVariantButtonClass;
    ngOnChanges(changes: SimpleChanges): void;
    isImage(icon: any): boolean;
    getIconClass(): string;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscButtonComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscButtonComponent, "dsc-button", never, { "type": { "alias": "type"; "required": false; }; "label": { "alias": "label"; "required": false; }; "iconSuffix": { "alias": "iconSuffix"; "required": false; }; "iconPrefix": { "alias": "iconPrefix"; "required": false; }; "icon": { "alias": "icon"; "required": false; }; "tabIndex": { "alias": "tabIndex"; "required": false; }; "dscTooltip": { "alias": "dscTooltip"; "required": false; }; "ariaLabel": { "alias": "ariaLabel"; "required": false; }; "ariaExpanded": { "alias": "ariaExpanded"; "required": false; }; "ariaControls": { "alias": "ariaControls"; "required": false; }; "iconStyle": { "alias": "iconStyle"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; "size": { "alias": "size"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "iconButton": { "alias": "iconButton"; "required": false; }; }, {}, never, never, true, never>;
}
