import { ElementRef, NgZone, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { BooleanInput } from '@angular/cdk/coercion';
import { AriaDescriber, InteractivityChecker } from '@angular/cdk/a11y';
import * as i0 from "@angular/core";
export type DscBadgePosition = 'above after' | 'above before' | 'below before' | 'below after' | 'before' | 'after' | 'above' | 'below';
export type DscBadgeSize = 'small' | 'standard' | 'large';
export type DscBadgeVariant = 'accent' | 'danger' | 'highlight' | 'information' | 'success' | 'warning';
export declare class DscBadgeDirective implements OnInit, OnDestroy {
    private _document;
    private _elementRef;
    private _renderer;
    private _ariaDescriber;
    private _interactivityChecker;
    private _ngZone;
    private _animationMode?;
    private _isInitialized;
    private _badgeElement;
    private _inlineBadgeDescription;
    private _id;
    size: DscBadgeSize;
    variant: DscBadgeVariant;
    get variantDark(): boolean;
    set variantDark(val: BooleanInput);
    private _variantDark;
    get overlap(): boolean;
    set overlap(val: BooleanInput);
    private _overlap;
    position: DscBadgePosition;
    get content(): string | number | undefined | null;
    set content(newContent: string | number | undefined | null);
    private _content;
    get description(): string;
    set description(newDescription: string);
    private _description;
    get hidden(): boolean;
    set hidden(val: BooleanInput);
    private _hidden;
    get disabled(): boolean;
    set disabled(value: any);
    private _disabled;
    constructor(_document: Document, _elementRef: ElementRef<HTMLElement>, _renderer: Renderer2, _ariaDescriber: AriaDescriber, _interactivityChecker: InteractivityChecker, _ngZone: NgZone, _animationMode?: string | undefined);
    ngOnInit(): void;
    isAbove(): boolean;
    isAfter(): boolean;
    private _updateRenderedContent;
    private _createBadgeElement;
    private _clearExistingBadges;
    private _updateDescription;
    private _isHostInteractive;
    private _removeInlineDescription;
    private _updateInlineDescription;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscBadgeDirective, [null, null, null, null, null, null, { optional: true; }]>;
    static ɵdir: i0.ɵɵDirectiveDeclaration<DscBadgeDirective, "[dscBadge]", never, { "disabled": { "alias": "dscBadgeDisabled"; "required": false; }; "size": { "alias": "dscBadgeSize"; "required": false; }; "variant": { "alias": "dscBadgeVariant"; "required": false; }; "variantDark": { "alias": "dscBadgeVariantDark"; "required": false; }; "overlap": { "alias": "dscBadgeOverlap"; "required": false; }; "position": { "alias": "dscBadgePosition"; "required": false; }; "content": { "alias": "dscBadge"; "required": false; }; "description": { "alias": "dscBadgeDescription"; "required": false; }; "hidden": { "alias": "dscBadgeHidden"; "required": false; }; }, {}, never, never, true, never>;
}
