import { AfterViewInit, EventEmitter } from '@angular/core';
import { FormControl, FormGroupDirective, NgControl, NgForm } from '@angular/forms';
import { MatSelect } from '@angular/material/select';
import { MatOptionSelectionChange } from '@angular/material/core';
import { BaseComponent } from 'sidsc-components/core';
import { Option } from './shared/option';
import * as i0 from "@angular/core";
export declare class DscSelectComponent extends BaseComponent<any> implements AfterViewInit {
    ngControl: NgControl;
    selectElement: MatSelect;
    iconPrefix?: string;
    options?: Option[];
    compareWith: (o1: any, o2: any) => boolean;
    get multiple(): boolean;
    set multiple(value: boolean | string);
    _multiple: boolean;
    get showFilter(): boolean;
    set showFilter(value: boolean | string);
    _showFilter: boolean;
    isActive: boolean;
    allSelected: boolean;
    isIndeterminate: boolean;
    tooltipId: string;
    value: any;
    writeValue(value: any): void;
    openedChange: EventEmitter<any>;
    selectionChange: EventEmitter<any>;
    search: FormControl;
    constructor(ngControl: NgControl, parentForm: NgForm, parentFormGroup: FormGroupDirective);
    ngAfterViewInit(): void;
    private disableSelectOpening;
    filter(option: Option): boolean;
    onOpenedChange(): void;
    change($event: MatOptionSelectionChange): void;
    toggleAllSelections(selectAll: boolean): void;
    checkAllSelected(): void;
    private _isSelected;
    private _select;
    private _deselect;
    private _unmarkSelected;
    getTruncatedSelection(selectedItems: any[]): string;
    get formFieldClasses(): string[];
    static ɵfac: i0.ɵɵFactoryDeclaration<DscSelectComponent, [{ optional: true; self: true; }, { optional: true; }, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscSelectComponent, "dsc-select", never, { "iconPrefix": { "alias": "iconPrefix"; "required": false; }; "options": { "alias": "options"; "required": false; }; "compareWith": { "alias": "compareWith"; "required": false; }; "multiple": { "alias": "multiple"; "required": false; }; "showFilter": { "alias": "showFilter"; "required": false; }; "value": { "alias": "value"; "required": false; }; }, { "openedChange": "openedChange"; "selectionChange": "selectionChange"; }, never, never, true, never>;
}
