import { AfterViewInit, ElementRef, OnInit, Renderer2 } from '@angular/core';
import { FormGroupDirective, NgControl, NgForm } from '@angular/forms';
import { MatInput } from '@angular/material/input';
import { BaseComponent } from 'sidsc-components/core';
import * as i0 from "@angular/core";
export declare class DscInputFileComponent extends BaseComponent<any> implements OnInit, AfterViewInit {
    ngControl: NgControl;
    private _renderer;
    inputFile: ElementRef<HTMLInputElement>;
    matInput: MatInput;
    get showTotalFileSize(): boolean;
    set showTotalFileSize(value: boolean | string);
    private _showTotalFileSize;
    isActive: boolean;
    get multiple(): boolean;
    set multiple(value: boolean | string);
    private _multiple;
    get maxTotalSize(): number;
    set maxTotalSize(value: number | string);
    private _maxTotalSize;
    accept?: string;
    totalFileSize: string;
    hintId: string;
    tooltipId: string;
    fileName?: string;
    constructor(ngControl: NgControl, parentForm: NgForm, parentFormGroup: FormGroupDirective, _renderer: Renderer2);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    private _setMultipleAttribute;
    private _setAcceptAttribute;
    private _removeAcceptAttribute;
    private _initValidators;
    private _getValidators;
    writeValue(value: any): void;
    onClick($event: Event): void;
    onInputChange($event: Event): void;
    get formFieldClasses(): string[];
    static ɵfac: i0.ɵɵFactoryDeclaration<DscInputFileComponent, [{ optional: true; self: true; }, { optional: true; }, { optional: true; }, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscInputFileComponent, "dsc-input-file", never, { "showTotalFileSize": { "alias": "showTotalFileSize"; "required": false; }; "multiple": { "alias": "multiple"; "required": false; }; "maxTotalSize": { "alias": "maxTotalSize"; "required": false; }; "accept": { "alias": "accept"; "required": false; }; }, {}, never, never, true, never>;
}
