import { EventEmitter } from '@angular/core';
import { AbstractControl, ValidationErrors, Validator } from '@angular/forms';
import { MatRadioChange } from '@angular/material/radio';
import { BooleanInput } from '@angular/cdk/coercion';
import { BaseControlValueAccessor } from 'sidsc-components/core';
import * as i0 from "@angular/core";
export type DscRadioButtonLabelPosition = 'before' | 'after';
export type DscRadioButtonVariant = 'highlight' | 'accent' | 'danger';
export type DscRadioButtonSize = 'large' | 'standard' | 'small';
export declare class DscRadioButtonComponent extends BaseControlValueAccessor<any> implements Validator {
    name: string;
    label?: string;
    ariaDescribedby: string;
    ariaLabel: string;
    ariaLabelledby: string;
    value: any;
    get labelPosition(): DscRadioButtonLabelPosition;
    set labelPosition(value: DscRadioButtonLabelPosition);
    private _labelPosition;
    get checked(): boolean;
    set checked(value: BooleanInput);
    private _checked;
    get required(): boolean;
    set required(value: BooleanInput);
    private _required;
    get size(): DscRadioButtonSize;
    set size(value: DscRadioButtonSize);
    private _size;
    protected radioButtonLabelSize: string;
    get variant(): DscRadioButtonVariant;
    set variant(value: DscRadioButtonVariant);
    private _variant;
    protected radioButtonVariant: string;
    readonly change: EventEmitter<any>;
    readonly focus: EventEmitter<void>;
    writeValue(value: any): void;
    select(): void;
    onChanged($event: MatRadioChange): void;
    validate(control: AbstractControl<any, any>): ValidationErrors | null;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscRadioButtonComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscRadioButtonComponent, "dsc-radio-button", never, { "name": { "alias": "name"; "required": false; }; "label": { "alias": "label"; "required": false; }; "ariaDescribedby": { "alias": "aria-describedby"; "required": false; }; "ariaLabel": { "alias": "aria-label"; "required": false; }; "ariaLabelledby": { "alias": "aria-labelledby"; "required": false; }; "value": { "alias": "value"; "required": false; }; "labelPosition": { "alias": "labelPosition"; "required": false; }; "required": { "alias": "required"; "required": false; }; "size": { "alias": "size"; "required": false; }; "variant": { "alias": "variant"; "required": false; }; }, { "change": "change"; "focus": "focus"; }, never, never, true, never>;
}
