import { EventEmitter, OnInit } from '@angular/core';
import { NumberInput } from '@angular/cdk/coercion';
import { FormControl } from '@angular/forms';
import { DscCollapsibleMenu } from './shared/dsc-collapsible-menu';
import { DscMenu } from './shared/dsc-menu';
import { Router } from '@angular/router';
import * as i0 from "@angular/core";
export type DscSidenavDrawerMode = 'over' | 'push' | 'side';
export declare class DscSidenavComponent implements OnInit {
    private _router;
    constructor(_router: Router);
    private _onDestroy;
    customClass: string | string[] | Set<string> | {
        [p: string]: any;
    } | null | undefined;
    coverSrc?: string;
    private expandedItems;
    singleExpand: boolean;
    get menu(): DscMenu[] | DscCollapsibleMenu[];
    set menu(value: DscMenu[] | DscCollapsibleMenu[]);
    private _menu;
    get opened(): boolean;
    set opened(value: boolean | string);
    _opened: boolean;
    get fixedInViewport(): boolean;
    set fixedInViewport(value: boolean | string);
    _fixedInViewport: boolean;
    get fixedTopGap(): number;
    set fixedTopGap(value: NumberInput);
    private _fixedTopGap;
    get fixedBottomGap(): number;
    set fixedBottomGap(value: NumberInput);
    private _fixedBottomGap;
    get mode(): DscSidenavDrawerMode;
    set mode(value: DscSidenavDrawerMode);
    private _mode;
    get showFilter(): boolean;
    set showFilter(value: boolean | string);
    _showFilter: boolean;
    openedChange: EventEmitter<boolean>;
    onClick: EventEmitter<DscMenu>;
    search: FormControl;
    menuFiltered: DscMenu[] | DscCollapsibleMenu[];
    private expandedItem?;
    ngOnInit(): void;
    onExpand(menu: DscMenu): void;
    private _applyDefaultSelection;
    onMenuClick(menu: DscMenu): void;
    private _findPath;
    isExpanded(menu: DscMenu): boolean;
    private _filterInit;
    private _doFilter;
    private _compare;
    static ɵfac: i0.ɵɵFactoryDeclaration<DscSidenavComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DscSidenavComponent, "dsc-sidenav", never, { "customClass": { "alias": "customClass"; "required": false; }; "coverSrc": { "alias": "coverSrc"; "required": false; }; "singleExpand": { "alias": "singleExpand"; "required": false; }; "menu": { "alias": "menu"; "required": false; }; "opened": { "alias": "opened"; "required": false; }; "fixedInViewport": { "alias": "fixedInViewport"; "required": false; }; "fixedTopGap": { "alias": "fixedTopGap"; "required": false; }; "fixedBottomGap": { "alias": "fixedBottomGap"; "required": false; }; "mode": { "alias": "mode"; "required": false; }; "showFilter": { "alias": "showFilter"; "required": false; }; }, { "openedChange": "openedChange"; "onClick": "onClick"; }, never, ["*"], true, never>;
}
